name: Dotnet Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
        - dev
        - stage
        - beta
        - prod
# env: 

#   ENVIRONMENT: ${{ if github.event.inputs.environment == 'dev' }}dev.newfolder
#                ${{ elseif github.event.inputs.environment == 'stage' }}staging.newfolder
#                ${{ elseif github.event.inputs.environment == 'beta' }}beta.newfolder
#                ${{ else }}prod.newfolder
#                ${{ endif }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: echo 
      run : |
            echo $MY_VAR
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.202'

    - name: Publish
      run: dotnet publish -c Release --no-self-contained -o ./publish
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: my-artifact
          path: ./publish

  Deploy:
    runs-on: self-hosted
    needs: Build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
          name: my-artifact
          path: /publish
    - name: Stop Website in IIS
      run: |
        Stop-WebItem "IIS:\Sites\$env:ENVIRONMENT"
        Start-Sleep -Seconds 20
        
    - name: Print rename folder step
      run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd-HH-mm"
          New-Item -ItemType Directory -Path "C:\$env:ENVIRONMENT-$timestamp"
          Copy-Item -Path "C:\$env:ENVIRONMENT\*" -Destination "C:\$env:ENVIRONMENT-$timestamp" -Recurse
          Remove-Item -Path "C:\$env:ENVIRONMENT\*" -Recurse 

    - name: Copy artifact files to folder
      run: |
          Copy-Item -Path \publish\* -Destination C:\$env:ENVIRONMENT -Recurse
    - name: Restart Website IIS
      run: |
          Start-WebItem "IIS:\Sites\$env:ENVIRONMENT"




# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

#name: .NET

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build:
#
#    runs-on: self-hosted
#
#    steps:
 #   - uses: actions/checkout@v3
 #   - name: Setup .NET
#      uses: actions/setup-dotnet@v3
 #     with:
 #       dotnet-version: 7.0.202
 #   - name: Restore dependencies
 #     run: dotnet restore
  #  - name: Build
  #    run: dotnet build --no-restore
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
